INSERT INTO CourtType (CourtTypeID, CourtType) VALUES (NEXTVAL('court_type_seq'), 'Clay');
INSERT INTO CourtType (CourtTypeID, CourtType) VALUES (NEXTVAL('court_type_seq'), 'Grass');
INSERT INTO CourtType (CourtTypeID, CourtType) VALUES (NEXTVAL('court_type_seq'), 'Hard Court');
INSERT INTO CourtType (CourtTypeID, CourtType) VALUES (NEXTVAL('court_type_seq'), 'Carpet');

INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '1A', 1);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '2A', 1);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '3A', 1);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '1B', 2);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '2B', 2);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '3B', 2);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '1C', 3);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '2C', 3);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '3C', 3);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '1D', 4);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '2D', 4);
INSERT INTO Court (CourtID, CourtAddress, CourtTypeID) VALUES (NEXTVAL('court_seq'), '3D', 4);

INSERT INTO Employee (EmployeeID, EmployeeFirstName, EmployeeLastName, EmployeeDateOfBirth, DateOfEmployment, EmployeeAddress, EmployeeUsername, EmployeePassword) VALUES (NEXTVAL('employee_seq'), 'Andrew', 'Jackson', '1989-02-14', '2017-10-02', '95 Windfall Dr., Los Angeles, CA 90006', 'andrew', 'jackson123');
INSERT INTO Employee (EmployeeID, EmployeeFirstName, EmployeeLastName, EmployeeDateOfBirth, DateOfEmployment, EmployeeAddress, EmployeeUsername, EmployeePassword) VALUES (NEXTVAL('employee_seq'), 'Owen', 'Peterson', '1982-05-24', '2018-04-21', '199 E. Forest Ave., Los Angeles, CA 90063', 'owen', 'peterson123');
INSERT INTO Employee (EmployeeID, EmployeeFirstName, EmployeeLastName, EmployeeDateOfBirth, DateOfEmployment, EmployeeAddress, EmployeeUsername, EmployeePassword) VALUES (NEXTVAL('employee_seq'), 'Michael', 'Cooper', '1990-12-31', '2017-12-14', '467 Division Street, Los Angeles, CA 90006', 'michael', 'michael23');
INSERT INTO Employee (EmployeeID, EmployeeFirstName, EmployeeLastName, EmployeeDateOfBirth, DateOfEmployment, EmployeeAddress, EmployeeUsername, EmployeePassword) VALUES (NEXTVAL('employee_seq'), 'Thomas', 'Miller', '1978-08-21', '2018-02-01', '207 Berkshire St., Los Angeles, CA 90066', 'thomas', 'miller123');
INSERT INTO Employee (EmployeeID, EmployeeFirstName, EmployeeLastName, EmployeeDateOfBirth, DateOfEmployment, EmployeeAddress, EmployeeUsername, EmployeePassword) VALUES (NEXTVAL('employee_seq'), 'John', 'Hunt', '1986-10-18', '2016-07-20', '9812 Lawrence Dr., Los Angeles, CA 90037', 'john', 'hunt123');

INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Robert', 'Coop', '1989-02-28', '2017-01-10', 179, 73, '863C Gulf St., Los Angeles, CA 90004', 'robert', 'coop123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Gabriel', 'Ramos', '1978-06-04', '2017-02-10', 182, 92, '36 Miles Road, Los Angeles, CA 90026', 'gabriel', 'gabriel123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Joshua', 'Parker', '1992-09-01', '2017-12-05', 169, 74, '337 County Dr., Los Angeles, CA 90037', 'joshua', 'parker123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Dylan', 'Garcia', '1985-11-09', '2018-03-02', 182, 83, '925 W. Glen Ridge Street, Los Angeles, CA 90042', 'dylan', 'garcia123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Benjamin', 'Silva', '1991-05-31', '2017-04-20', 190, 91, '337 County Dr., Los Angeles, CA 90037', 'benjamin', 'silva123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Isaac', 'Wolfe', '1981-06-08', '2018-01-13', 181, 80, '21 Somerset Ave., Los Angeles, CA 90001', 'isaac', 'wolfe123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Connor', 'Blaire', '1990-09-20', '2017-10-03', 173, 79, '365 Adams St., Los Angeles, CA 90066', 'connor', 'blaire123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Vincent', 'Webster', '1982-01-19', '2018-04-01', 192, 93, '9467 Surrey Lane, Los Angeles, CA 90026', 'vincent', 'webster123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Mark', 'Connor', '1990-01-31', '2017-04-26', 178, 88, '589 6th Dr., Los Angeles, CA 90042', 'mark', 'connor123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Oscar', 'Doyle', '1980-08-03', '2018-06-01', 194, 82, '432 Cedarwood Dr., Los Angeles, CA 90066', 'oscar', 'doyle123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Collin', 'Monroe', '1987-02-28', '2018-02-02', 184, 82, '7874 Hanover St., Los Angeles, CA 90037', 'collin', 'monroe123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Eric', 'Fischer', '1994-09-19', '2017-10-20', 187, 79, '9311 Linda Road, Los Angeles, CA 90063', 'eric', 'fisher123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Micah', 'Evans', '1981-12-04', '2017-04-29', 172, 69, '8283 Armstrong Lane, Los Angeles, CA 90037', 'micah', 'evans123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Oliver', 'Baxter', '1998-08-02', '2018-03-02', 174, 78, '8693 Plymouth Street, Los Angeles, CA 90066', 'oliver', 'baxter123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Christian', 'Tanner', '1994-11-06', '2018-03-02', 182, 89, '16 Summerhouse Street, Los Angeles, CA 90042', 'christian', 'tanner123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Nathan', 'Booth', '1978-04-18', '2017-02-10', 176, 79, '660 University Ave., Los Angeles, CA 90019', 'nathan', 'booth123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Zachary', 'Lester', '1993-07-14', '2017-09-26', 170, 80, '5 Redwood Lane, Los Angeles, CA 90044', 'zachary', 'lester123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Brandon', 'Meyers', '1986-03-29', '2018-05-02', 181, 78, '497 Applegate Dr., Los Angeles, CA 90022', 'brandon', 'meyers123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Ian', 'Stone', '1980-07-20', '2017-10-31', 185, 72, '636 Glenwood Lane, Los Angeles, CA 90003', 'ian', 'stone123');
INSERT INTO Player (PlayerID, PlayerFirstName, PlayerLastName, PlayerDateOfBirth, DateOfJoining, Height, Weight, PlayerAddress, PlayerUsername, PlayerPassword) VALUES (NEXTVAL('player_seq'), 'Eli', 'Grimes', '1992-03-10', '2018-05-10', 175, 70, '967 St Paul Drive, Los Angeles, CA 90001', 'eli', 'grimes123');

INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 1, 4, 3);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 2, 2, 10);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 3, 8, 13);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 4, 1, 16);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 5, 9, 4);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 6, 9, 14);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 7, 18, 5);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 8, 3, 11);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 9, 9, 18);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 10, 10, 1);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 11, 20, 9);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 12, 5, 12);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 13, 13, 6);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 14, 9, 2);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 15, 16, 20);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 16, 15, 8);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 17, 17, 17);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 18, 8, 19);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 19, 10, 15);
INSERT INTO Rank (RankID, Position, PreviousPosition, PlayerID) VALUES (NEXTVAL('rank_seq'), 20, 18, 7);

INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '07:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '07:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '08:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '08:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '09:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '09:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '10:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '10:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '11:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '11:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '12:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '12:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '13:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '13:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '14:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '14:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '15:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '15:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '16:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '16:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '17:00');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '17:30');
INSERT INTO Appointment (AppointmentID, AppointmentTime) VALUES (NEXTVAL('appointment_seq'), '18:00');

INSERT INTO Match (MatchID, MatchDate, ApprovedBySecondPlayer, ApprovedByEmployee, FirstPlayerSets, SeondPlayerSets, CourtID, CourtTypeID, FirstPlayerID, SecondPlayerID, AppointmentID) VALUES (NEXTVAL('match_seq'), '2018-06-03', true, true, 2, 1, 5, 2, 3, 13, 7);
INSERT INTO Match (MatchID, MatchDate, ApprovedBySecondPlayer, ApprovedByEmployee, FirstPlayerSets, SeondPlayerSets, CourtID, CourtTypeID, FirstPlayerID, SecondPlayerID, AppointmentID) VALUES (NEXTVAL('match_seq'), '2018-06-05', true, true, 4, 1, 2, 1, 4, 7, 10);
INSERT INTO Match (MatchID, MatchDate, ApprovedBySecondPlayer, CourtTypeID, FirstPlayerID, SecondPlayerID, AppointmentID) VALUES (NEXTVAL('match_seq'), '2018-06-25', true, 3, 9, 13, 3);
INSERT INTO Match (MatchID, MatchDate, CourtTypeID, FirstPlayerID, SecondPlayerID, AppointmentID) VALUES (NEXTVAL('match_seq'), '2018-07-01', 4, 20, 15, 7);

INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 3, 6, 1);
INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 6, 4, 1);
INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 6, 2, 1);
INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 6, 3, 2);
INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 4, 6, 2);
INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 6, 3, 2);
INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 7, 6, 2);
INSERT INTO Game (GameID, FirstPlayerPoints, SecondPlayerPoints, MatchID) VALUES (NEXTVAL('game_seq'), 6, 2, 2);